# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"BaseParams": "00_params.ipynb",
         "CRFParams": "00_params.ipynb",
         "StaticBatchParams": "00_params.ipynb",
         "DynamicBatchSizeParams": "00_params.ipynb",
         "preprocessing_fn": "01_preproc_decorator.ipynb",
         "truncate_seq_pair": "02_bert_utils.ipynb",
         "punc_augument": "02_bert_utils.ipynb",
         "create_instances_from_document": "02_bert_utils.ipynb",
         "MaskedLmInstance": "02_bert_utils.ipynb",
         "TrainingInstance": "02_bert_utils.ipynb",
         "seq_tag_label_handling": "03_create_bert_features.ipynb",
         "pad_wrapper": "03_create_bert_features.ipynb",
         "convert_labels_to_ids": "03_create_bert_features.ipynb",
         "create_bert_features": "03_create_bert_features.ipynb",
         "create_bert_pretraining": "03_create_bert_features.ipynb",
         "mask_inputs_for_mask_lm": "03_create_bert_features.ipynb",
         "create_multimodal_bert_features": "03_create_bert_features.ipynb",
         "create_bert_features_generator": "03_create_bert_features.ipynb",
         "create_multimodal_bert_features_generator": "03_create_bert_features.ipynb",
         "LOGGER": "03_create_bert_features.ipynb",
         "serialize_fn": "04_read_write_tfrecord.ipynb",
         "make_tfrecord": "04_read_write_tfrecord.ipynb",
         "make_feature_desc": "04_read_write_tfrecord.ipynb",
         "write_single_problem_chunk_tfrecord": "04_read_write_tfrecord.ipynb",
         "write_single_problem_gen_tfrecord": "04_read_write_tfrecord.ipynb",
         "write_tfrecord": "04_read_write_tfrecord.ipynb",
         "reshape_tensors_in_dataset": "04_read_write_tfrecord.ipynb",
         "add_loss_multiplier": "04_read_write_tfrecord.ipynb",
         "set_shape_for_dataset": "04_read_write_tfrecord.ipynb",
         "get_dummy_features": "04_read_write_tfrecord.ipynb",
         "add_dummy_features_to_dataset": "04_read_write_tfrecord.ipynb",
         "read_tfrecord": "04_read_write_tfrecord.ipynb",
         "TestBase": "99_test_base.ipynb"}

modules = ["params.py",
           "preproc_decorator.py",
           "bert_preprocessing/bert_utils.py",
           "bert_preprocessing/create_bert_features.py",
           "read_write_tfrecord.py",
           "test_base.py"]

doc_url = "https://JayYip.github.io/bert_multitask_learning/"

git_url = "https://github.com/JayYip/bert_multitask_learning/tree/master/"

def custom_doc_links(name): return None
