# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"BaseParams": "00_params.ipynb",
         "CRFParams": "00_params.ipynb",
         "StaticBatchParams": "00_params.ipynb",
         "DynamicBatchSizeParams": "00_params.ipynb"}

modules = ["params.py"]

doc_url = "https://JayYip.github.io/bert_multitask_learning/"

git_url = "https://github.com/JayYip/bert_multitask_learning/tree/master/"

def custom_doc_links(name): return None
