# AUTOGENERATED! DO NOT EDIT! File to edit: source_nbs/02_special_tokens.ipynb (unless otherwise specified).

__all__ = ['BOS_TOKEN', 'EOS_TOKEN', 'CLS_TOKEN', 'SPACE_TOKEN', 'UNK_TOKEN', 'SPECIAL_TOKENS', 'TRAIN', 'EVAL',
           'PREDICT', 'MODAL_LIST']

# Cell
BOS_TOKEN = '[unused98]'
EOS_TOKEN = '[unused99]'
CLS_TOKEN = '[CLS]'
SPACE_TOKEN = '[unused1]'
UNK_TOKEN = '[UNK]'
SPECIAL_TOKENS = [BOS_TOKEN, EOS_TOKEN, CLS_TOKEN, SPACE_TOKEN, UNK_TOKEN]
TRAIN = 'train'
EVAL = 'eval'
PREDICT = 'infer'
MODAL_LIST = ['image', 'others']
